### PR TITLE
Fixed method for adding new member into database

### PR DESCRIPTION
**Pull request by number213**
I noticed that `pixiv_master_member` table in my database is empty so I checked the code and found that DB manager's method `insertNewMember` is never called. So I fixed it and added code for calling it.

### CODE REVIEW

**Comment by Nandaka** [comment]
it is on purpose, so using option will not add new member. 

you use option 4 for that (it will import the member id from list.txt) and download the images from member id listed in DB.

sometimes I want to check new artist, but dont want to update the images from option 4.

**Comment by number213** [comment]
So when you use option 1 and download by member id you don't need to write member's info into database?

**Comment by Nandaka** [comment]
yep, i dont want to track the member id from option 1

**Comment by number213** [comment]
Ok, got it.

**Comment by jwshields** [comment]
I apologize for resurrecting such an old issue..
I also saw #465 and #453 about this as well.

May I ask the rationale behind `dont want to track the member id from option 1`?
For myself, that's something I would like to have, just to populate the table and keep track of artists.

Could this maybe be implemented if a flag was added to settings like `dbsavememberid = True` or something of that nature? If so, I could submit a PR-

**Comment by Nandaka** [comment]
more because personal reason:

> it is on purpose, so using option will not add new member.
> 
> you use option 4 for that (it will import the member id from list.txt) and download the images from member id listed in DB.
> 
> sometimes I want to check new artist, but dont want to update the images from option 4.

**Comment by jwshields** [comment]
I understand that from reading the comments, but my question was more of, is this could be implemented in a PR **with an option to enable or disable it**, would that be acceptable? This is something I would like _personally_ and based on the previous issues, others may like it too.

**Comment by Nandaka** [comment]
sure, send me PR and I will review the code first.

**Pull request closed without merging**
