### PR TITLE
Pixiv Sketch config and Database Manager changes

### PR DESCRIPTION
**Pull request by cglmrfreeman**
I've been looking at the code for the database manager as well as how sketches are handled to create this pull request, and I've made a few changes that I hope work to improve the codebase as a whole:

- If a Sketch was found in the database and overwrite and alwaysCheckFileSize were disabled, the sketch would not be skipped. The message informing the user that it was skipping the post also included an erroneous " ." after the sentence. These have been fixed.
- The interactive cleanup for Fanbox had the incorrect index to display the `save_name` from the sqlite query, it would display the `page` value instead. This has been fixed.
- The menu interface for database management used the old implementation prior to the inclusion of the `colorama` requirement. It has been updated to more closely resemble the main PixivUtil2 menu.
- Clarified in the `readme.md` that the `%image_id%` filenameFormat for sketch posts would use the "Post id".
- A KeyboardInterrupt in PixivDownloadHandler would throw a `PIXIVUTIL_ABORTED` but a `PIXIVUTIL_KEYBOARD_INTERRUPT` is already defined. I feel it would be better to distinct an abort caused by software error versus a user initiated interrupt in this instance.
- Pixiv sketches had no cleanup options. They do now
- The variable `defaultSketchOption` has been defined in the configuration to skip the "Include Pixiv Sketch" option when downloading by `member_id` as requested in  #1073. Just like the option used currently, if set to `y` it will include sketches, if set to `n` it will exclude sketches. If the value is not set or set to an invalid option, it will continue to prompt the user to include sketches or not. The `readme.md` has also been updated to include this config change.

Please let me know what you think. Thank you.

EDIT: What this does _not_ fix is handling a keyboard interrupt while PixivUtil2 downloads sketches. Unlike the regular `member_id` illustration download, a keyboard interrupt does not pause downloading, and simply moves onto the next sketch. You can not fully abort a sketch download like you can with a normal illustration download.

### CODE REVIEW

**Comment by cglmrfreeman** [comment]
Hmm, it appears that with the `PIXIVUTIL_ABORTED` changed to `PIXIVUTIL_KEYBOARD_INTERRUPT`, this makes the `PIXIVUTIL_ABORTED` constant unused. Functionally the program appears to be no different swapping the two, but "ABORTED" may have been chosen on purpose for reasons I can't find clear at the moment.

**Comment by cglmrfreeman** [comment]
I have merged upstream and resolved conflicts, but github is saying conflicts exist and I have not merged upstream. Any ideas, @Nandaka?

**Comment by cglmrfreeman** [comment]
I don't understand why now it's showing your commit changes in my changes here? They should be caught up with master?

**Comment by cglmrfreeman** [comment]
Any thoughts so far? Questions? Comments? Concerns?

**Comment by Nandaka** [comment]
>  Functionally the program appears to be no different swapping the two, but "ABORTED" may have been chosen on purpose for reasons I can't find clear at the moment.

I think it was used before as generic exception.

Looks ok 😄

**Comment by cglmrfreeman** [comment]
LOL! I wasn't finished but sure! I guess this works ahaha! :sweat_smile:

**Comment by Nandaka** [comment]
welp, I thought u waiting to change for me to change the draft to reviewed :P

**Comment by cglmrfreeman** [comment]
@Nandaka LOL! No worries, the only thing I had left to do was allow the cancel prompt when downloading Pixiv sketches, which can be handled in another PR. Currently keyboard interrupt cancels the currently downloading sketch and moves onto the next.

**Comment by Nandaka** [comment]
yeah, I prefer separate small PR, rather than big changes in single PR, else it is difficult to follow :P

**Pull request merged**
