### PR TITLE
Fixing a mistake when dealing with downloading by post id

### PR DESCRIPTION
**Pull request by bluerthanever**
Sorry I missed a spot...
This is new and not in the unit test....
Sorry

### CODE REVIEW

**Comment by Nandaka** [comment]
can you add a new unittest so it can catch the new usecase? 
Thanks a lot for the fanbox development and test, because I don't use it at all 😅

**Comment by bluerthanever** [comment]
Haha. This is killing me... I hate unit tests.
Should I add it here or pull a new request? And is there a deadline...?

**Comment by Nandaka** [comment]
nah, just use the same PR for the unit test.
You need to add unit test, else your future self will kill you 😆 , also good for testing regression.

**Comment by bluerthanever** [comment]
haha.. ok.... I will try to finish it tonight.

**Comment by Nandaka** [comment]
take it easy, it won't kill you to push it later.

**Comment by bluerthanever** [comment]
That's fine... but can you add unit tests that requires internet?
cuz the new function kinda requires that, otherwise I think it's already covered by other tests, if it's just reading jsons and parsing them into instances...
The mistake in this PR happened when building requests

**Comment by Nandaka** [comment]
hmm, I don't think Travis can connect to the internet for the free version, also that require you to pass the authentication data.

**Comment by bluerthanever** [comment]
Okay... I guess I was always a little sloppy... 
I will try not to make mistakes next time. 😄

**Pull request merged**
