### PR TITLE
Download fanbox articles in HTML #656

### PR DESCRIPTION
**Pull request by bluerthanever**
Added a switch "writeHtml" in config, to define whether to write fanbox article posts to html files in PixivConifg.
Added a property "linkToFile" for fanbox post class, to store each link and its local file path in a pairs as a dict, and a new method to write html files in PixivFanboxModel.
Added logic to store urls and local file paths when processing each image, and when the switch is on and the post is an article post, calls the method to write the html file.
Added a html pattern file for all the html files.

### CODE REVIEW

**Comment by bluerthanever** [comment]
#659

**Comment by bluerthanever** [comment]
I just modified it in my way...
And I tested on my side, works for me though, please confirm.

And if you see any other of my pull requests related to this, please ignore or delete those. I might have done something by mistake.

**Comment by bluerthanever** [comment]
Made some more tests, works fine with firefox, chrome and edge on my side, but doesn't seem compatible with IE.... Probably need some help.

**Comment by Nandaka** [comment]
is it possible to store the default html pattern to `PixivConstant.py` so if the `pattern.html` is deleted/missing, it will use the default pattern in the code?

**Comment by bluerthanever** [comment]
I think that's not a problem.
So I will keep the old way, if the `pattern.html` file doesn't exist, it refers to `PixivConstant.py`, so if the user want to change something in the pattern, they can just do it themselves, right?

**Comment by bluerthanever** [comment]
Hmm... Just saw the new release of beta version. Maybe I should have used "template" instead of "pattern"....

**Comment by Nandaka** [comment]
I also changed the file detection logic a bit:
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L2070-L2076

**Comment by bluerthanever** [comment]
Yes. I have noticed.

**Pull request merged**
