### PR TITLE
Option to add Pixiv tag/caption data to db, auto add member data

### PR DESCRIPTION
**Pull request by psilabs-dev**
A collection of commits intended to improve metadata preservation from Pixiv for future metadata extraction and migration to manga readers/galleries.

1. Implements the (opt-in) option to add tag data (`pixiv_master_tag`), image/tag associations (`pixiv_image_to_tag`), and tag translations (`pixiv_tag_translation`).
2. Implements the (opt-in) option to add caption data as a column to `pixiv_master_image`.
3. If `autoAddMember` is set to True: save member data automatically when downloading an image.

Example `pixiv_image_to_tag`:

Screenshot 2024-10-31 at 10 42 58 PM

Example `pixiv_master_tag`:

Screenshot 2024-10-31 at 10 43 33 PM

Example `pixiv_tag_translation`:

Screenshot 2024-10-31 at 10 43 57 PM

### CODE REVIEW

**Comment by Nandaka** [comment]
can it handle if somehow the image doesn't have any tag?

**Comment by biggestsonicfan** [comment]
Should this not be it's own table with a relative link?

**Comment by psilabs-dev** [comment]
> can it handle if somehow the image doesn't have any tag?

Yes, this is in PixivImageHandler line 432

**Comment by psilabs-dev** [comment]
> Should this not be it's own table with a relative link?

Can you elaborate?

**Comment by Nandaka** [comment]
> > Should this not be it's own table with a relative link?
> 
> Can you elaborate?

I think for tags, it is saved to separate table `pixiv_master_tag` & `pixiv_tag_translation` with mapping table to link between image and tags `pixiv_image_to_tag`

for caption, it is extended column `caption` in `pixiv_master_image`.

Should be ok for me

**Comment by psilabs-dev** [comment]
Sorry to bring this after it was merged, there is an issue with mapping tables that allows the existence of duplicates

I'm working on a hotfix to address this issue, until the fix is released I do not recommend using the new options

**Pull request merged**
