### PR TITLE
use python3 print format

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
related #325 

this is not included fix for `print` with trailing space.

based on this https://stackoverflow.com/questions/4009672/python-trailing-comma-after-print-executes-next-instruction

there is no python2/3 compatibilities code, so the fix is probably using this format

```python
if six.PY3:
    print('Some text', end='')
else:
    print 'Some text',
```

and because of that fix, it require six library (which later can be useful to port to python3 code).

but for now because it add additional dependencies, i will put it on hold

### CODE REVIEW

**Comment by Nandaka** [comment]
You cannot simply add `()` if there are multiple `,`. Maybe refactor to use string.format()?
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> string = "test"
>>> print "hello", string
hello test
>>> print("hello", string)
('hello', 'test')
>>> print "hello", "world"
hello world
>>> print("hello", "world")
('hello', 'world')
>>>
```

**Comment by rachmadaniHaryono** [comment]
based on this it can be fixed with single line

```python
from __future__ import print_function
```

**Comment by Nandaka** [comment]
Looks like that fix the issue, another one: you need to use `end=' '` so it will append space for the continuation.

```
>>> if True:
...   print("Hello", end='')
...   print("World")
...
HelloWorld
>>> if True:
...   print("Hello", end=' ')
...   print("World")
...
Hello World
>>>
```

**Comment by rachmadaniHaryono** [comment]
https://github.com/rachmadaniHaryono/PixivUtil2/commit/fd1fa52c59010a048e476b5f9b139893a909b680

not sure why the pr is not updating itself

**Comment by Nandaka** [comment]
I think because I've closed the old one, try to raise another PR?

**Pull request closed without merging**
