### PR TITLE
Added Series Info and conditionals to JSON/txt, and removed an unneccesary string format

### PR DESCRIPTION
**Pull request by byjtje**
Though about the context of the JSON/txt:
Is there any reason to include Urls, since that one is just a parsing of the Caption? Same could be said for Link.

And for the txt, is there any reason for us to newline with \r\n instead of \n?

### CODE REVIEW

**Comment by Nandaka** [comment]
> Is there any reason to include Urls, since that one is just a parsing of the Caption? Same could be said for Link.

this is used for exporting urls to text file if `writeUrlInDescription = True`

> And for the txt, is there any reason for us to newline with \r\n instead of \n?

Windows.

**Comment by byjtje** [comment]
> this is used for exporting urls to text file if `writeUrlInDescription = True`
Not sure if it's intentional, but both Urls and Link get added to txt/JSON with it off. The readme also states a different purpose for writeUrlInDescription

> Windows.
I don't have it on hand to test, but doesn't it still parse them correctly with just \n?

**Comment by Nandaka** [comment]
> I don't have it on hand to test, but doesn't it still parse them correctly with just \n?

No, some windows application (e.g. older notepad), only recognize \r\n combo, https://docs.python.org/3/library/os.html#os.linesep. If you only using one platform, then using os.linesep is OK, but if you open on different platform, it is better to use \r\n so it will shows correctly in windows.

> urls

I think it to make it easier for me when I try copy/paste the link to download manager last time (rather than parsing the whole description manually). Just a convenience only.

**Comment by byjtje** [comment]
Ah I see thanks. For what it's worth the documentation you linked states:
`Do not use os.linesep as a line terminator when writing files opened in text mode (the default); use a single '\n' instead, on all platforms.`

> I think it to make it easier for me when I try copy/paste the link to download manager last time (rather than parsing the whole description manually). Just a convenience only.

Ah, I guess then no reason not to remove them? Or should we keep it at least in the txt?

**Comment by Nandaka** [comment]
> '\n' instead, on all platforms.

Python will write \r\n or \n depending on current platform, right? It might cause an issue if the text file was written in unix-based and then open in Windows.

> json

I think better keep it, someone might uses the json file to import the metadata.

**Comment by byjtje** [comment]
For what it's worth they could still import it, considering the metadata remains in there (and I don't see a use case for the urls specifically)

>It might cause an issue if the text file was written in unix-based and then open in Windows.

Hm for what it's worth googling tells me that it's only really old Windows stuff having problems with it, but I guess it doesn't matter too much.

Just wondering, is there any documentation for the Pixiv API? I've been unable to find anything on their own website

**Comment by Nandaka** [comment]
>  Pixiv API?

I don't think so (or at least in english). I need to do reverse engineering from the current web implementation, other pixiv project, and/or pixiv app.

**Comment by byjtje** [comment]
I see, thanks!

**Pull request merged**
