### PR TITLE
Add BOM automatically

### LINKED ISSUE #543: Irfan Viewer and unicode filenames
This is more of "What I am doing wrong with file lists" question

Lists of downloaded images open perfectly with Irfan 4.44 with unicode plagin, but modern Irfan 4.53 opens only files without japanese characters in names.
Moveover, when I open files through Irfan 4.44 "Open in editor" functionality, Japanese filenames turn into glibberish.

Any ideas?

### PR DESCRIPTION
**Pull request by NHOrus**
Should fix #543

### CODE REVIEW

**Comment by NHOrus** [comment]
No, this does for first line only.

**Comment by NHOrus** [comment]
Fixed

**Comment by Nandaka** [comment]
won't this impact other viewer which doesn't support BOM or older irfanView? might need to add config to enable this?

**Comment by NHOrus** [comment]
And this code doesn't work, because I miswrote getsize function.
Will make new PR later.

Old Irfan supports BOM, I tested. So, no problems there.

**Pull request closed without merging**
