### PR TITLE
Remove retriving bookmarks function

### PR DESCRIPTION
**Pull request by YukihoAA**
for #1159 

removing retriving bookmarks infomation to prevent ban.

it works fine for tags mode but idk why code get bookmarks seperatly before download...

### CODE REVIEW

**Comment by Nandaka** [comment]
It is to skip the post if the bookmark limit is defined when you download by tags. If you remove this code, then it will download all images when you set a limit.

If you want to skip this bookmark data retrieval, then just set the limit to 0/None from the console input.

https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L366
https://github.com/Nandaka/PixivUtil2/blob/master/PixivUtil2.py#L371

**Comment by YukihoAA** [comment]
@Nandaka 

bookmark skipping and grouping works fine for image mode because there is skipping function in PixivImageHandler.py L174

image

image

**Comment by Nandaka** [comment]
But if the image doesn't exists in the db, it still need to get the bookmark data. Only if you are registered premium user that have the data from the json response, I think?

https://github.com/Nandaka/PixivUtil2/blob/b723feb4a72567746ab8696586fb3647a5d49334/PixivBrowserFactory.py#L832

fyi, bookmark data is empty from server
image

and it is only available when you load the page, which I think it is more expensive to run? and anyway you still need to get the page anyway if you want to filter by bookmark count.
image

Maybe you can add a logic to skip this you are premium user? e.g. `if use_bookmark_data and not self._isPremium:`

https://github.com/Nandaka/PixivUtil2/blob/b723feb4a72567746ab8696586fb3647a5d49334/PixivBrowserFactory.py#L867

**Comment by YukihoAA** [comment]
I'm not using premium now and I'm using bookmark count skip feature.

It was an ideal codes **to use bookmark count skipping with out being IP ban.** issue #1159 
if i use 20220825 version, like if image skipped 120 in one time, pixiv will give me IP ban.

I tried to add 2 second wait to every loop for bookmark retriving function using wait(result, self.__config) 
but does not worked :(

so my Idea was just using functions in PixivImageHandler to make some delay to prevent ban.

**Comment by Nandaka** [comment]
can you confirm after running it for some time? because after the change, then it will always fetch the image page and then skipping it if the bookmark count is lower ==> which in turn, currently it will cause 429 error due to it request too many image page too often.

**Comment by YukihoAA** [comment]
In case v20220825: will got baned after 120~180 image skipped by retriving bookmarks with 5 sec delay
image

After edited: it worked fine (~2hr running) with 5 sec delay.
image
image

I runned same option that already downloaded so almost all images was skipped.


2 sec delay is not working both case.

**Comment by YukihoAA** [comment]
3sec is seems fine too
image
image
image

**Comment by YukihoAA** [comment]
3sec is seems fine too (1hr test) - @Nandaka 
image
image
image
image
image

**Comment by Nandaka** [comment]
sorry for the late reply, I was just back. Anyway, it is merged now

**Pull request merged**
